version: "2.1"
services:
## Conteneur de base de données
## Les informationsd de connexion doivent etre saisies dans le fichier .env
  database:
    build: './SQL'
    container_name: database
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_DATA_DIR=/var/lib/mysql
    - MYSQL_RUN_DIR=/run/mysqld
    - MYSQL_LOG_DIR=/var/log/mysql
    networks:
    - backend
    volumes:
    - db_data:/var/lib/mysql
  api:
    build: './API'
    container_name: api
    restart: unless-stopped
    ports:
    - 10000:10000
    depends_on:
    - "database"
    links:
    - database:database
    environment:
    - HOST=database
    - USER=${MYSQL_USERNAME}
    - PASSWORD=${MYSQL_USER_PASSWORD}
    - DATABASE=${MYSQL_DATABASE}
    networks:
    - frontend
    - backend
  web:
    depends_on:
    - "database"
    build: './WEB'
    container_name: webapp
    restart: unless-stopped
    links:
    - database:database
    - api:api
    ports:
    - 80:80
    - 443:443
    networks:
    - frontend
    - backend
    environment:
    - database=database
    - MYSQL_USERNAME=${MYSQL_USERNAME}
    - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
networks:
  backend:
    internal: true
  frontend:
volumes:
  db_data: {}
