version: "2"
services:

### Container portail http
  # web:
  #   build: ~/web
  #   ports:
  #     - "80:80"
  #     - "443:443"

### API REST
  api:
    image: effid/api
    ports:
    - 10000:10000
    networks:
      - effid

### Container Base de données mysql
  database:
    image: effid/sql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=APOKALYPSIS
    - MYSQL_USER=effid
    - MYSQL_PASSWORD=ABYSS
    - MYSQL_DATABASE=eff-id
    - MYSQL_DATA_DIR=/var/lib/mysql
    - MYSQL_RUN_DIR=/run/mysqld
    - MYSQL_LOG_DIR=/var/log/mysql
    # volumes:
    #   - /var/lib/mysql:/var/lib/mysql
    networks:
      - effid

  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

### Container supervision grafana
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - effid
  #   volumes:
  #     - grafana-volume:/var/lib/grafana

### Container base InfluxDB
  # influxdb:
  #   image: influxdb
  #   container_name: influxdb
  #   restart: always
  #   ports:
  #     - 8086:8086
  #   networks:
  #     - effid
  #   volumes:
  #     - influxdb-volume:/var/lib/influxdb

# Reseaux de communication entre containers
networks:
  effid:

# Volumes de stockage de données des containers
# volumes:
#   grafana-volume:
#     external: true
#   influxdb-volume:
#     external: true
