version: "2"
services:

### Container portail http
  web:
    build: ~/web
    ports:
      - "80:80"
      - "443:443"

### API REST
  api:
    image: effid/api
    ports:
    - "10000:10000"
  networks:
    - effid

### Container Base de données mysql
  database:
    image: jsurf/rpi-mariadb
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=APOKALYPSIS
    - MYSQL_USER=effid
    - MYSQL_PASSWORD=ABYSS
    - MYSQL_DATABASE=eff-id
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - effid

### Container supervision grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - effid
    volumes:
      - grafana-volume:/var/lib/grafana

### Container base InfluxDB
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - effid
    volumes:
      - influxdb-volume:/var/lib/influxdb

# Reseaux de communication entre containers
networks:
  effid:

# Volumes de stockage de données des containers
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
